apiVersion : apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app.kubernetes.io/name: django-app
    owner: forluc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: django-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-app
        owner: forluc
    spec:
      containers:
        - name: django
          image: forluc/django_app
          envFrom:
            - configMapRef:
                name: django-cm
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-deployment
  labels:
    app.kubernetes.io/name: django-app
spec:
  type: ClusterIP
  ports:
    - name: external-port
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: django-app

