apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    name: django-app
    component: migrations
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        name: django-app
        component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: forluc/django_app
          envFrom:
            - secretMapRef:
                name: django-secret
          imagePullPolicy: IfNotPresent
          command:
            - ./manage.py
            - migrate